# Generated by Django 2.2.12 on 2022-01-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRS', '0002_auto_20220126_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userEmail',
            field=models.CharField(default='', max_length=18, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userGender',
            field=models.CharField(default='', max_length=18, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userGrade',
            field=models.CharField(default='', max_length=18, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userMajor',
            field=models.CharField(default='', max_length=18, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userPhone',
            field=models.CharField(default='', max_length=18, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=18, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='用户名'),
        ),
    ]
